version: '3'

services:
  mdcx:
    image: ghcr.io/gythialy/mdcx:latest
    container_name: mdcx
    volumes:
      - /path/to/data:/data
      - ./config.ini:/app/config.ini
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1090
      - VNC_PASSWORD=123123
    ports:
      - 5800:5800
      - 5900:5900
    restart: unless-stopped
    network_mode: bridge
    stdin_open: true
